# app/api/v1/telemetry.py
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from typing import Dict, Any, Optional
from datetime import datetime
import uuid
from app.core.database import get_db_connection
from app.services.alerter import AlerterService
from app.core.security import verify_internal_key
from fastapi import Depends
import json

router = APIRouter(prefix="/telemetry", tags=["Telemetry Ingestion"])


# ============================================================================
# PYDANTIC DATA SCHEMAS (DATA CONTRACTS)
# ============================================================================
class GuardrailMetric(BaseModel):
    policy_violated: bool = Field(..., description="Flags if a guardrail policy rule was breached")
    violation_type: Optional[str] = Field(None, description="Type of violation")
    action_taken: Optional[str] = Field(None, description="Action taken")


class ReliabilityMetric(BaseModel):
    hallucination_score: Optional[float] = Field(None, description="Calculated hallucination metric score")
    groundedness_score: Optional[float] = Field(None, description="Calculated groundedness metric score")
    retrieval_precision: Optional[float] = Field(None, description="Precision score of context documents retrieved")


class TelemetryPayload(BaseModel):
    trace_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique tracking identifier")
    model_name: str = Field(..., description="Target model name")
    prompt_text: str = Field(..., description="Raw text prompt")
    response_text: str = Field(..., description="Raw output generated by model")
    prompt_tokens: int = Field(default=0, description="Count of prompt tokens")
    completion_tokens: int = Field(default=0, description="Count of completion tokens")
    latency_ms: float = Field(..., description="Turnaround duration in ms")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="UTC execution timestamp")
    guardrails: Optional[GuardrailMetric] = None
    reliability: Optional[ReliabilityMetric] = None
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Context hooks")


# ============================================================================
# INGESTION API ENDPOINT WITH REAL-TIME THRESHOLD INTERCEPTOR
# ============================================================================
@router.post("/trace", status_code=status.HTTP_201_CREATED, dependencies=[Depends(verify_internal_key)])
async def ingest_trace(payload: TelemetryPayload):
    """
    Ingest structural telemetry packets, commit them securely into DuckDB,
    and dynamically evaluate operational threshold parameters.
    """
    try:
        gv = payload.guardrails if payload.guardrails else GuardrailMetric(policy_violated=False)
        rv = payload.reliability if payload.reliability else ReliabilityMetric()

        with get_db_connection() as conn:
            conn.execute("""
                INSERT INTO traces (
                    trace_id, model_name, prompt_text, response_text, 
                    prompt_tokens, completion_tokens, latency_ms, timestamp,
                    policy_violated, violation_type, action_taken,
                    hallucination_score, groundedness_score, retrieval_precision,
                    metadata
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
            """, (
                payload.trace_id, payload.model_name, payload.prompt_text, payload.response_text,
                payload.prompt_tokens, payload.completion_tokens, payload.latency_ms, payload.timestamp,
                gv.policy_violated, gv.violation_type, gv.action_taken,
                rv.hallucination_score, rv.groundedness_score, rv.retrieval_precision,
                json.dumps(payload.metadata)
            ))

        # DYNAMIC TRIGGER: Evaluate the payload for threshold SLA violations via model_dump
        AlerterService.evaluate_trace_thresholds(payload.model_dump())

        return {
            "status": "accepted",
            "trace_id": payload.trace_id,
            "persisted": True
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database insertion crash: {str(e)}"
        )